{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "StockAnalyst_Generate_Features.ipynb",
      "version": "0.3.2",
      "provenance": [],
      "collapsed_sections": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "[View in Colaboratory](https://colab.research.google.com/github/hhngan/ML/blob/master/StockAnalyst/StockAnalyst_Generate_Features.ipynb)"
      ]
    },
    {
      "metadata": {
        "id": "o6D5SC-Mj2lC",
        "colab_type": "code",
        "colab": {}
      },
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "produce_charts = False\n",
        "if produce_charts:\n",
        "  import matplotlib.pyplot as plt\n",
        "\n",
        "def return_features(df):\n",
        "  \"\"\"\n",
        "  Args:\n",
        "    df: pandas.DataFrame, columns include at least [\"date\", \"open\", \"high\", \"low\", \"close\", \"volume\"]\n",
        "  Returns:\n",
        "    pandas.DataFrame\n",
        "  \"\"\"\n",
        "  df[\"return\"] = df[\"close\"] / df[\"close\"].shift(1)\n",
        "  df[\"close_to_open\"] = df[\"close\"] / df[\"open\"]\n",
        "  df[\"close_to_high\"] = df[\"close\"] / df[\"high\"]\n",
        "  df[\"close_to_low\"] = df[\"close\"] / df[\"low\"]\n",
        "  df = df.iloc[1:] #first first row: does not have return a value\n",
        "  return df\n",
        "\n",
        "def target_value(df):\n",
        "  df[\"y\"] = df[\"return\"].shift(-1)\n",
        "  df = df.iloc[:len(df)-1]\n",
        "  return df\n",
        "\n",
        "def trend_features(df):\n",
        "  \"\"\"\n",
        "  Args:\n",
        "      df: pandas.DataFrame, columns include at least [\"date\", \"open\", \"high\", \"low\", \"close\", \"volume\"]\n",
        "  Returns:\n",
        "      pandas.DataFrame\n",
        "  \"\"\"\n",
        "  df = macd(df)\n",
        "  df = ma(df)\n",
        "  df = parabolic_sar(df)\n",
        "  return df\n",
        "\n",
        "def macd(df):\n",
        "  \"\"\"\n",
        "  Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_convergence_divergence_macd\n",
        "  Args:\n",
        "      df: pandas.DataFrame, columns include at least [\"close\"]\n",
        "  Returns:\n",
        "      pandas.DataFrame\n",
        "  \"\"\"\n",
        "  ema_12_day = df[\"close\"].ewm(com=(12-1)/2).mean()\n",
        "  ema_26_day = df[\"close\"].ewm(com=(26-1)/2).mean()\n",
        "  df[\"macd_line\"] = ema_12_day - ema_26_day\n",
        "  df[\"macd_9_day\"] = df[\"macd_line\"].ewm(com=(9-1)/2).mean()\n",
        "  df[\"macd_diff\"] = df[\"macd_line\"] - df[\"macd_9_day\"]\n",
        "  # print(df.tail(10)[[\"date\", \"close\", \"macd_line\", \"macd_9_day\"]])\n",
        "  if produce_charts:\n",
        "    chart_macd(df)\n",
        "  return df\n",
        "\n",
        "def chart_macd(df):\n",
        "  \"\"\"\n",
        "  Save chart to charts/macd\n",
        "  Args:\n",
        "      df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"macd_line\", \"macd_9_day\"]\n",
        "  Returns:\n",
        "      None\n",
        "  \"\"\"\n",
        "  fig, axes = plt.subplots(2, 1, figsize=(10, 10))\n",
        "  fig.tight_layout()\n",
        "  plt.suptitle(\"MSFT\", fontsize=24)\n",
        "  plt.subplots_adjust(left=0.1, top=0.9, hspace = 0.4)\n",
        "  ax1 = axes[0]\n",
        "  ax1.set_title(\"Price\")\n",
        "  ax1.set_ylabel(\"$\")\n",
        "  df.tail(300)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=ax1)\n",
        "  ax2 = axes[1]\n",
        "  ax2.set_title(\"MACD\")\n",
        "  df.tail(300)[[\"date\", \"macd_line\", \"macd_9_day\"]].plot(x=\"date\", kind=\"line\", ax=ax2, secondary_y=False)\n",
        "  # df.tail(300)[[\"date\", \"macd_diff\"]].plot(x=\"date\", kind=\"bar\", ax=ax2, secondary_y=True)\n",
        "  fig.savefig(\"charts/macd.png\")\n",
        "  \n",
        "def ma(df):\n",
        "  \"\"\"\n",
        "  Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_averages\n",
        "  Args:\n",
        "      df: pandas.DataFrame, columns include at least [\"close\"]\n",
        "  Returns:\n",
        "      pandas.DataFrame\n",
        "  \"\"\"\n",
        "  df[\"ma_50_day\"] = df[\"close\"].rolling(50).mean()\n",
        "  df[\"ma_200_day\"] = df[\"close\"].rolling(200).mean()\n",
        "  df[\"ma_50_200\"] = df[\"ma_50_day\"] - df[\"ma_200_day\"]\n",
        "  # print(df.tail(10)[[\"date\", \"close\", \"ma_50_200\"]])\n",
        "  if produce_charts:\n",
        "    chart_ma(df)\n",
        "  return df\n",
        "\n",
        "def chart_ma(df):\n",
        "  \"\"\"\n",
        "  Save chart to charts/ma\n",
        "  Args:\n",
        "      df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"ma_50_200\"]\n",
        "  Returns:\n",
        "      None\n",
        "  \"\"\"\n",
        "  fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "  fig.tight_layout()\n",
        "  plt.suptitle(\"MSFT Moving Average 50 day - 200 day\", fontsize=24)\n",
        "  plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace=0.4)\n",
        "  axes.set_ylabel(\"$\")\n",
        "  df.tail(1500)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "  df.tail(1500)[[\"date\", \"ma_50_day\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "  df.tail(1500)[[\"date\", \"ma_200_day\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "  df.tail(1500)[[\"date\", \"ma_50_200\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "  fig.savefig(\"charts/ma.png\")\n",
        "\n",
        "def parabolic_sar(df):\n",
        "  \"\"\"\n",
        "  Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:parabolic_sar\n",
        "  Args:\n",
        "      df: pandas.DataFrame, columns include at least [\"close\"]\n",
        "  Returns:\n",
        "      pandas.DataFrame\n",
        "  \"\"\"\n",
        "  df[\"sar\"] = np.nan\n",
        "  step = 5\n",
        "  acc_factor = 0.02\n",
        "  uptrend = False\n",
        "  prior_sar = max(df.loc[1:step, \"close\"])\n",
        "  extreme_point = min(df.loc[1:step, \"close\"])\n",
        "  for i, row in df.iloc[step:].iterrows():\n",
        "      if uptrend:\n",
        "          df.at[i, \"sar\"] = prior_sar + acc_factor*(extreme_point - prior_sar)\n",
        "          if df.at[i, \"low\"] < df.at[i, \"sar\"]:\n",
        "              # reverse to downtrend\n",
        "              uptrend = False\n",
        "              prior_sar = max(df.loc[i-step:i, \"close\"])\n",
        "              extreme_point = min(df.loc[i-step:i, \"close\"])\n",
        "          else:\n",
        "              # continue uptrend\n",
        "              if df.at[i, \"close\"] > extreme_point:\n",
        "                  extreme_point = df.at[i, \"close\"]\n",
        "                  acc_factor = min(0.2, acc_factor+0.02)\n",
        "      else:\n",
        "          df.at[i, \"sar\"] = prior_sar - acc_factor*(prior_sar - extreme_point)\n",
        "          if df.at[i, \"high\"] > df.at[i, \"sar\"]:\n",
        "              # reverse to uptrend\n",
        "              uptrend = True\n",
        "              prior_sar = min(df.loc[i-step:i, \"close\"])\n",
        "              extreme_point = max(df.loc[i-step:i, \"close\"])\n",
        "          else:\n",
        "              # continue downtrend\n",
        "              if df.at[i, \"close\"] < extreme_point:\n",
        "                  extreme_point = df.at[i, \"close\"]\n",
        "                  acc_factor = min(0.2, acc_factor+0.02)\n",
        "      prior_sar = df.at[i, \"sar\"]\n",
        "  if produce_charts:\n",
        "      chart_sar(df)\n",
        "  return df\n",
        "\n",
        "def chart_sar(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/ma\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"sar\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT SAR\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    axes.set_ylabel(\"$\")\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"sar\"]].plot(x=\"date\", style=\".\", ax=axes, secondary_y=False)\n",
        "    fig.savefig(\"charts/sar.png\")\n",
        "\n",
        "def momentum_features(df):\n",
        "    \"\"\"\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"open\", \"high\", \"low\", \"close\", \"volume\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    df = stochastic_oscillator(df)\n",
        "    df = commodity_channel_index(df)\n",
        "    df = rsi(df)\n",
        "    return df\n",
        "\n",
        "def stochastic_oscillator(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:stochastic_oscillator_fast_slow_and_full\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"close\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    lookback = 14\n",
        "    df[\"stochastic_oscillator\"] = ((df[\"close\"] - df[\"close\"].rolling(lookback).min()) /\n",
        "        (df[\"close\"].rolling(lookback).max() - df[\"close\"].rolling(lookback).min())) * 100\n",
        "    if produce_charts:\n",
        "        chart_stochastic_oscillator(df)\n",
        "    return df\n",
        "\n",
        "def chart_stochastic_oscillator(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/stochastic_oscillator\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"stochastic_oscillator\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT Stochastic Oscillator\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"stochastic_oscillator\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/stochastic_oscillator.png\")\n",
        "\n",
        "def commodity_channel_index(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:commodity_channel_index_cci\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"open\", \"high\", \"low\", \"close\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    typical_price = (df[\"high\"] + df[\"low\"] + df[\"close\"]) / 3\n",
        "    mean_dev = abs(typical_price - typical_price.rolling(20).mean()).rolling(20).mean()\n",
        "    df[\"cci\"] = (typical_price - typical_price.rolling(20).mean()) / (0.15 * mean_dev)\n",
        "    if produce_charts:\n",
        "        chart_commodity_channel_index(df)\n",
        "    return df\n",
        "\n",
        "def chart_commodity_channel_index(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/commodity_channel_index\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"stochastic_oscillator\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT Commodity Channel Index (CCI)\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(300)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(300)[[\"date\", \"cci\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/commodity_channel_index.png\")\n",
        "\n",
        "def rsi(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:relative_strength_index_rsi\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"close\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    df[\"dollar_pnl\"] = df[\"close\"].shift(1) - df[\"close\"]\n",
        "    avg_gains = df[\"dollar_pnl\"].iloc[:14][df[\"dollar_pnl\"].iloc[:14] > 0].sum() / 14\n",
        "    avg_losses = abs(df[\"dollar_pnl\"].iloc[:14][df[\"dollar_pnl\"].iloc[:14] < 0].sum()) / 14\n",
        "    for i, row in df.iloc[14:].iterrows():\n",
        "        if row[\"dollar_pnl\"] > 0:\n",
        "            avg_gains = (avg_gains * 13 + row[\"dollar_pnl\"]) / 14\n",
        "        else:\n",
        "            avg_losses = (avg_losses * 13 + abs(row[\"dollar_pnl\"])) / 14\n",
        "        if avg_losses == 0:\n",
        "            rs = 100\n",
        "        else:\n",
        "            rs = avg_gains / avg_losses\n",
        "        df.loc[i, \"rsi\"] = 100 - 100 / (1 + rs)\n",
        "    # print(df.tail(20)[[\"date\", \"close\", \"rsi\"]])\n",
        "    if produce_charts:\n",
        "        chart_rsi(df)\n",
        "    return df\n",
        "\n",
        "def chart_rsi(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/rsi\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"rsi\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT Relative Strength Index (RSI)\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"rsi\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/rsi.png\")\n",
        "\n",
        "def volatility_features(df):\n",
        "    \"\"\"\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"open\", \"high\", \"low\", \"close\", \"volume\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    df[\"5d_volatility\"] = df[\"return\"].rolling(5).std()\n",
        "    df[\"21d_volatility\"] = df[\"return\"].rolling(21).std()\n",
        "    df[\"60d_volatility\"] = df[\"return\"].rolling(60).std()\n",
        "    df = bollinger_bands(df)\n",
        "    df = average_true_range(df)\n",
        "    return df\n",
        "\n",
        "def bollinger_bands(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:bollinger_bands\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"close\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    df[\"bollinger\"] = ((df[\"close\"] - df[\"close\"].rolling(21).mean()) / \n",
        "        2 * df[\"close\"].rolling(21).std())\n",
        "    if produce_charts:\n",
        "        chart_bollinger(df)\n",
        "    return df\n",
        "\n",
        "def chart_bollinger(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/bollinger\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"bollinger\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT Bollinger Bands\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"bollinger\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/bollinger.png\")\n",
        "\n",
        "def average_true_range(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_true_range_atr\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"high\" ,\"low, \"close\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    high_vs_low = df[\"high\"] - df[\"low\"]\n",
        "    high_vs_prev_close = df[\"high\"] - df[\"close\"].shift(-1)\n",
        "    low_vs_prev_close = df[\"low\"] - df[\"close\"].shift(-1)\n",
        "    tr = high_vs_low.to_frame(\"high_vs_low\")\n",
        "    tr[\"high_vs_prev_close\"] = high_vs_prev_close\n",
        "    tr[\"low_vs_prev_close\"] = low_vs_prev_close\n",
        "    tr[\"tr\"] = tr.max(axis=1)\n",
        "    df[\"atr\"] = tr[\"tr\"].rolling(14).mean()\n",
        "    if produce_charts:\n",
        "        chart_average_true_range(df)\n",
        "    return df\n",
        "\n",
        "def chart_average_true_range(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/average_true_range\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"atr\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT Average True Range (ATR)\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"atr\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/average_true_range.png\")\n",
        "\n",
        "def volume_features(df):\n",
        "    \"\"\"\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"open\", \"high\", \"low\", \"close\", \"volume\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    df[\"volume_rolling\"] = df[\"volume\"] / df[\"volume\"].shift(21)\n",
        "    df = on_balance_volume(df)\n",
        "    df = chaikin_oscillator(df)\n",
        "    return df\n",
        "\n",
        "def on_balance_volume(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:on_balance_volume_obv\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"close\", \"volume\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    df[\"dollar_pnl\"] = df[\"close\"].shift(1) - df[\"close\"]\n",
        "    df[\"on_balance_volume\"] = df[\"volume\"]\n",
        "    df[\"on_balance_volume\"] = df.apply(lambda row: row.volume * -1 if row.dollar_pnl < 0 else row.volume, axis=1)\n",
        "    df[\"on_balance_volume\"] = df[\"on_balance_volume\"].cumsum()\n",
        "    # print(df.head(10)[[\"date\", \"close\", \"dollar_pnl\", \"volume\", \"on_balance_volume\"]])\n",
        "    if produce_charts:\n",
        "        chart_on_balance_volume(df)\n",
        "    return df\n",
        "\n",
        "def chart_on_balance_volume(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/on_balance_volume\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"on_balance_volume\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT On Balance Volume (OBV)\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"on_balance_volume\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/on_balance_volume.png\")\n",
        "\n",
        "def chaikin_oscillator(df):\n",
        "    \"\"\"\n",
        "    Math reference: https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:chaikin_oscillator\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"low\", \"high\", \"close\", \"volume\"]\n",
        "    Returns:\n",
        "        pandas.DataFrame\n",
        "    \"\"\"\n",
        "    money_flow_multiplier = ((df[\"close\"] - df[\"low\"]) / (df[\"high\"] - df[\"low\"])) / (df[\"high\"] - df[\"low\"])\n",
        "    money_flow_volume = df[\"volume\"] * money_flow_multiplier\n",
        "    adl = money_flow_volume.cumsum()\n",
        "    df[\"chaikin_oscillator\"] = adl.ewm(com=(3-1)/2).mean() - adl.ewm(com=(10-1)/2).mean()\n",
        "    # print(df.head(10)[[\"date\", \"close\", \"volume\", \"chaikin_oscillator\"]])\n",
        "    if produce_charts:\n",
        "        chart_chaikin_oscillator(df)\n",
        "    return df\n",
        "\n",
        "def chart_chaikin_oscillator(df):\n",
        "    \"\"\"\n",
        "    Save chart to charts/chaikin_oscillator\n",
        "    Args:\n",
        "        df: pandas.DataFrame, columns include at least [\"date\", \"close\", \"chaikin_oscillator\"]\n",
        "    Returns:\n",
        "        None\n",
        "    \"\"\"\n",
        "    fig, axes = plt.subplots(1, 1, figsize=(10, 10))\n",
        "    fig.tight_layout()\n",
        "    plt.suptitle(\"MSFT Chaikin Oscillator\", fontsize=24)\n",
        "    plt.subplots_adjust(left=0.1, top=0.9, right=0.9, hspace = 0.4)\n",
        "    df.tail(100)[[\"date\", \"close\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=False)\n",
        "    df.tail(100)[[\"date\", \"chaikin_oscillator\"]].plot(x=\"date\", kind=\"line\", ax=axes, secondary_y=True)\n",
        "    fig.savefig(\"charts/chaikin_oscillator.png\")"
      ],
      "execution_count": 0,
      "outputs": []
    }
  ]
}
